GENRES = [
    "KRNB",
    "Lofi",
    "Meditation Music",
    "Merengue",
    "Metal",
    "Motown",
    "Neo-Soul",
    "Noise Rock",
    "Old School Hip-Hop",
    "Opera",
    "Pop",
    "Post-Punk",
    "Progressive Metal",
    "Progressive Rock",
    "Psychedelic Rock",
    "Punk",
    "R&B",
    "Rap",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Romantic Classical",
    "Salsa",
    "Ska",
    "Smooth Jazz",
    "Soca",
    "Soul Jazz",
    "Soul",
    "Southern Rap",
    "Swing",
    "Symphonic Metal",
    "Synth Pop",
    "Synthwave",
    "Tango",
    "Techno",
    "Trance",
    "Trap",
    "Trip-Hop",
    "Vaporwave",
    "Video Game Music",
    "Vocaloid",
    "Zouk"
]